name: PMD Code Analysis

on:
  push:
    branches: [ '*' ]

jobs:
  pmd:
    name: Run PMD Code Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Run PMD
        run: |
          curl -LO https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0-rc4/pmd-bin-7.0.0-rc4.zip
          unzip pmd-bin-7.0.0-rc4.zip
          ./pmd-bin-7.0.0-rc4/bin/run.sh pmd \
            --dir src/main/java \
            --rulesets rulesets/java/quickstart.xml \
            --format sarif \
            --report-file pmd-report.sarif
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@9e8d0789d4a0fa9ceb6b1738f7e269594bdd67f0
        with:
          sarif_file: pmd-report.sarif
